# Generated by Django 6.0.4 on 2026-04-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasApp', '0002_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='LexingtonBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('blueprint_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='script',
            name='script_name',
            field=models.CharField(choices=[('Admin', 'Add Admins script'), ('Blueprint', 'Blueprint script'), ('LexBlueprint', 'Lexington specific blueprint script'), ('Observer', 'Observer script'), ('Enrollment', 'Enrollment script'), ('CheckSisId', 'CheckSisId script'), ('VirtualCrosslist', 'Virtual Crosslist script'), ('RemovePeriod', 'Remove Period script')], max_length=50),
        ),
    ]
