# Generated by Django 6.0.4 on 2026-04-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasApp', '0006_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='name',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='value',
            field=models.JSONField(default='none'),
            preserve_default=False,
        ),
    ]
