# Generated by Django 6.0.4 on 2026-04-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasApp', '0007_variable_name_variable_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='brief_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_name',
            field=models.CharField(choices=[('Admin', 'Add Admins script'), ('Blueprint', 'Blueprint script'), ('Designer', 'Designer script'), ('LexBlueprint', 'Lexington specific blueprint script'), ('Observer', 'Observer script'), ('Enrollment', 'Enrollment script'), ('CheckSisId', 'CheckSisId script'), ('VirtualCrosslist', 'Virtual Crosslist script'), ('RemovePeriod', 'Remove Period script')], max_length=50),
        ),
    ]
