# Generated by Django 6.0.4 on 2026-04-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(choices=[('observer', 'Observer script'), ('enrollment', 'Enrollment script'), ('blueprint', 'Blueprint script')], max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CanvasApp.school')),
            ],
        ),
    ]
