# Generated by Django 6.0.4 on 2026-04-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasApp', '0004_schooladmininfo_subaccountids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubAccountIds',
            new_name='SubAccountId',
        ),
    ]
